# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a7f1ce24fb6aa300532caea1de2ffa8e5dcb1d5d0454548092bd25e401f03ee8efa3f459d5bf79e3eea2db627769243296a25f071876ffb4e020ba790d01e39

test:
  secret_key_base: 259f8bdf518edb87743811105499a14e31854f5ef4d57e8a665a99ec6f0b08816bfafa161a1a252880ca0c2e2fbba317c748725939826066489a4278bc74deb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
